# This function is necessary to include the same source files in both executables
def create_objs(sourceFiles):
	ret = []
	for file in sourceFiles:
		ret.append(env.Object(file))
	return ret
		
env = Environment(CCFLAGS = '-g -Wall -O0', CC = 'g++')

# Source files that are shared between main application and test application
#src =  ['file.c', 'parser.c', 'codeWriter.c']
src =  ['tokenizer.cpp']

# Build the VM program
exe = 'compiler'
env.Program(exe, create_objs(src + ['main.cpp']))

# Build the test program
testExe = 'test/compilerTest'
#testSrc = src + ['test/testMain.c','test/test_file.c', 'test/test_parser.c',
#	'test/test_codeWriter.c', 'test/test_util.c']
testSrc = src + ['test/testMain.cpp', 'test/testTokenizer.cpp']
#SConscript('main.scons', variant_dir = 'test/build', duplicate = 0)
env.Program(testExe, create_objs(testSrc))
